CREATE TABLE `users` (
	`userid` INT(11) NOT NULL AUTO_INCREMENT,
	`username` VARCHAR(50) NULL DEFAULT NULL,
	`password` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`userid`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=9
;


CREATE TABLE `student` (
	`id` INT(11) NOT NULL,
	`last` VARCHAR(50) NULL DEFAULT NULL,
	`first` VARCHAR(50) NULL DEFAULT NULL,
	`address1` VARCHAR(50) NULL DEFAULT NULL,
	`address2` VARCHAR(50) NULL DEFAULT NULL,
	`city` VARCHAR(50) NULL DEFAULT NULL,
	`state` VARCHAR(50) NULL DEFAULT NULL,
	`zip` VARCHAR(50) NULL DEFAULT NULL,
	`country` VARCHAR(50) NULL DEFAULT NULL,
	`cellNum` VARCHAR(50) NULL DEFAULT NULL,
	`homNum` VARCHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`gender` VARCHAR(50) NULL DEFAULT NULL,
	`hispanic` CHAR(1) NULL DEFAULT NULL,
	`race` VARCHAR(50) NULL DEFAULT NULL,
	`highSchool` VARCHAR(50) NULL DEFAULT NULL,
	`GPA` VARCHAR(50) NULL DEFAULT NULL,
	`ACT` VARCHAR(50) NULL DEFAULT NULL,
	`SAT` VARCHAR(50) NULL DEFAULT NULL,
	`alumni` CHAR(1) NULL DEFAULT NULL,
	`denomination` VARCHAR(50) NULL DEFAULT NULL,
	`major1` VARCHAR(50) NULL DEFAULT NULL,
	`major2` VARCHAR(50) NULL DEFAULT NULL,
	`major3` VARCHAR(50) NULL DEFAULT NULL,
	`major4` VARCHAR(50) NULL DEFAULT NULL,
	`counselor` VARCHAR(50) NULL DEFAULT NULL,
	`enrollPeriod` VARCHAR(50) NULL DEFAULT NULL,
	`visit` CHAR(1) NULL DEFAULT NULL,
	`visitDate` DATE NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `status` (
	`fk_id` INT(11) NOT NULL,
	`statusChange` VARCHAR(50) NOT NULL,
	`statusDate` DATE NULL DEFAULT NULL,
	`completed` CHAR(1) NULL DEFAULT 'N',
	PRIMARY KEY (`fk_id`, `statusChange`),
	INDEX `FK2_statusChange` (`statusChange`),
	CONSTRAINT `FK1_id` FOREIGN KEY (`fk_id`) REFERENCES `student` (`id`),
	CONSTRAINT `FK2_statusChange` FOREIGN KEY (`statusChange`) REFERENCES `message` (`AdmissionStatus`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `message` (
	`admissionStatus` VARCHAR(50) NOT NULL,
	`action` VARCHAR(50) NULL DEFAULT NULL,
	`msg` VARCHAR(250) NULL DEFAULT NULL,
	PRIMARY KEY (`admissionStatus`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;





